baseURL       : https://ncar.github.io/miles/
languageCode  : en-us
title         : "MILES | Machine Integration and Learning for Earth Systems"
theme         : ncar
enableGitInfo : true
summarylength : 25

menu:
  nav:
    - name      : About
      url       : about
      weight    : 1
    - name      : News
      url       : news
      weight    : 2
    - identifier: what
      name      : What we do
      weight    : 3
    - parent    : what
      name      : Education
      url       : education
      weight    : 1
    - parent    : what
      name      : Projects
      url       : projects
      weight    : 2
    - parent    : what
      name      : Datasets
      url       : datasets
      weight    : 3
    - parent    : what
      name      : Software
      url       : software
      weight    : 4
    - name      : Publications
      url       : publications
      weight    : 4
    - name      : Presentations
      url       : presentations
      weight    : 5
    - name      : Collaboration
      url       : collaboration
      weight    : 6

# Site Params
params:
  name: MILES
  dateFormat: "26 FEB 1994"
  description: "MILES is the Machine Integration and Learning for Earth Systems group at the National Center for Atmospheric Research (NCAR)."
  author: "MILES"
  email: "miles@ucar.edu"

  news:
    enable: false
    title: RECENT NEWS
    subtitle: Some of our most recent news

  projects:
    enable: true
    title: RECENT PROJECTS
    subtitle: Some of our most recent research projects

  footer:
    contactInfo:
      title  : Contact Info
      address: 1850 Table Mesa Dr.<br>Boulder, CO 80305
      email  : milescore@ucar.edu

    sitemap:
      title: Sitemap
      column:
        - link:
          - name: About us
            url : about
          - name: News
            url : news
          - name: Publications
            url : publications
          - name: Presentations
            url : presentations
          - name: Collaboration
            url : collaboration
        - link:
          - name: Education
            url : education
          - name: Projects
            url : projects
          - name: Datasets
            url : datasets
          - name: Software
            url : software
